// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Excuse Generator AI agent.
 *
 * - generateExcuse - A function that handles the excuse generation process.
 * - GenerateExcuseInput - The input type for the generateExcuse function.
 * - GenerateExcuseOutput - The return type for the generateExcuse function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateExcuseInputSchema = z.object({
  context: z.string().describe('The context or situation for which an excuse is needed.'),
});
export type GenerateExcuseInput = z.infer<typeof GenerateExcuseInputSchema>;

const GenerateExcuseOutputSchema = z.object({
  excuse: z.string().describe('A plausible and creative excuse tailored to the provided context.'),
});
export type GenerateExcuseOutput = z.infer<typeof GenerateExcuseOutputSchema>;

export async function generateExcuse(input: GenerateExcuseInput): Promise<GenerateExcuseOutput> {
  return generateExcuseFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateExcusePrompt',
  input: {schema: GenerateExcuseInputSchema},
  output: {schema: GenerateExcuseOutputSchema},
  prompt: `You are an expert excuse generator. Given the following context, generate a plausible and creative excuse.

Context: {{{context}}}

Excuse: `,
});

const generateExcuseFlow = ai.defineFlow(
  {
    name: 'generateExcuseFlow',
    inputSchema: GenerateExcuseInputSchema,
    outputSchema: GenerateExcuseOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
